# Generated by Django 6.0.3 on 2026-03-07 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0002_rename_example_code_codeproblem_input_example_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codesubmission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RenameField(
            model_name='codesubmission',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='codesubmission',
            name='execution_time',
        ),
        migrations.RemoveField(
            model_name='codesubmission',
            name='language',
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='is_correct',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programming.codeproblem'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
