# Generated by Django 6.0.3 on 2026-03-07 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0003_alter_codesubmission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codeproblem',
            options={'verbose_name': '编程题目', 'verbose_name_plural': '编程题目管理'},
        ),
        migrations.AlterModelOptions(
            name='codesubmission',
            options={'ordering': ['-submitted_at'], 'verbose_name': '提交记录', 'verbose_name_plural': '提交记录管理'},
        ),
        migrations.RemoveField(
            model_name='codeproblem',
            name='input_example',
        ),
        migrations.RemoveField(
            model_name='codeproblem',
            name='output_example',
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='sample_input',
            field=models.TextField(blank=True, null=True, verbose_name='样例输入 (仅展示)'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='sample_output',
            field=models.TextField(blank=True, null=True, verbose_name='样例输出 (仅展示)'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='test_cases',
            field=models.JSONField(blank=True, default=list, verbose_name='测试用例集 (JSON格式)'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='description',
            field=models.TextField(verbose_name='题目描述'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20, verbose_name='难度'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='题目名称'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='code',
            field=models.TextField(verbose_name='提交代码'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='判题反馈'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='是否通过'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programming.codeproblem', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
