# Generated by Django 6.0.3 on 2026-03-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0004_alter_codeproblem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('python', 'Python 3'), ('cpp', 'C++ (G++)'), ('c', 'C (GCC)'), ('java', 'Java')], default='python', max_length=20, verbose_name='编程语言'),
        ),
    ]
