# Generated by Django 6.0.3 on 2026-03-07 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0005_codesubmission_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('python', 'Python 3'), ('c', 'C (GCC)'), ('cpp', 'C++ (G++)'), ('java', 'Java')], default='python', max_length=20, verbose_name='编程语言'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='programming.codeproblem', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['user', '-submitted_at'], name='programming_user_id_932b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['problem', '-submitted_at'], name='programming_problem_3a5fab_idx'),
        ),
    ]
