# Generated by Django 6.0.3 on 2026-03-07 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0006_alter_codesubmission_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codeproblem',
            options={'ordering': ['id'], 'verbose_name': '编程题目', 'verbose_name_plural': '编程题目管理'},
        ),
        migrations.RemoveField(
            model_name='codesubmission',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='accepted_count',
            field=models.PositiveIntegerField(default=0, verbose_name='通过人数'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='data_range',
            field=models.TextField(blank=True, help_text='支持 LaTeX 格式，如：0 ≤ A, B ≤ 10^8', null=True, verbose_name='数据范围'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='input_format',
            field=models.TextField(blank=True, help_text='例如：第一行包含两个整数 A 和 B。', null=True, verbose_name='输入格式'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='memory_limit',
            field=models.IntegerField(default=128, verbose_name='内存限制 (MB)'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='output_format',
            field=models.TextField(blank=True, help_text='例如：输出一个整数，表示 A+B 的结果。', null=True, verbose_name='输出格式'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='source',
            field=models.CharField(blank=True, help_text='例如：AcWing 1, LeetCode 1, NOIP 2023', max_length=100, null=True, verbose_name='题目来源'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='submission_count',
            field=models.PositiveIntegerField(default=0, verbose_name='总提交数'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='tags',
            field=models.CharField(blank=True, help_text='逗号分隔，例如：贪心,模拟,动态规划', max_length=200, null=True, verbose_name='算法标签'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='time_limit',
            field=models.IntegerField(default=1, verbose_name='时间限制 (秒)'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='execution_memory',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='运行内存 (KB)'),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='execution_time',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='运行时间 (ms)'),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error')], default='PD', max_length=10, verbose_name='判题状态'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='description',
            field=models.TextField(verbose_name='题目描述 (支持 Markdown/MathJax)'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='sample_input',
            field=models.TextField(blank=True, null=True, verbose_name='样例输入'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='sample_output',
            field=models.TextField(blank=True, null=True, verbose_name='样例输出'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='test_cases',
            field=models.JSONField(blank=True, default=list, help_text='系统将根据此列表自动判题', verbose_name='测试用例集 (JSON)'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='feedback',
            field=models.TextField(blank=True, help_text='编译错误或最后一个测试点的报错信息', null=True, verbose_name='判题反馈/错误信息'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('python', 'Python 3'), ('c', 'C (GCC 9.4.0)'), ('cpp', 'C++ (G++ 9.4.0)'), ('java', 'Java (OpenJDK 11)'), ('go', 'Go (1.19)'), ('javascript', 'JavaScript (Node.js)')], default='python', max_length=20, verbose_name='编程语言'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='提交用户'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['status'], name='programming_status_838949_idx'),
        ),
    ]
