# Generated by Django 6.0.3 on 2026-03-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0008_problemdiscussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeproblem',
            name='solution_text',
            field=models.TextField(blank=True, help_text='在此填写详细解题思路、代码分析和复杂度分析。支持换行。', null=True, verbose_name='官方题解'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='video_url',
            field=models.CharField(blank=True, help_text='填入视频嵌入链接 (Embed URL)，例如 Bilibili 的 player 链接。', max_length=500, null=True, verbose_name='视频讲解链接'),
        ),
    ]
