# Generated by Django 6.0.3 on 2026-03-07 16:17

import programming.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0009_codeproblem_solution_text_codeproblem_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeproblem',
            name='test_cases',
            field=models.JSONField(blank=True, default=list, help_text='系统将根据此列表自动判题。格式：[{"input": "...", "output": "..."}]', validators=[programming.models.validate_test_cases_json], verbose_name='测试用例集 (JSON)'),
        ),
    ]
