# Generated by Django 6.0.3 on 2026-03-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0010_alter_codeproblem_test_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeproblem',
            name='function_name',
            field=models.CharField(default='solve', help_text='用户需要实现的函数名，例如: twoSum, add', max_length=100, verbose_name='函数名'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='input_example',
            field=models.JSONField(blank=True, help_text="JSON 格式，如: {'nums': [1,2], 'target': 3} 或 [1, 2]", null=True, verbose_name='输入示例 (JSON)'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='output_example',
            field=models.JSONField(blank=True, help_text='JSON 格式，如: 3 或 [0, 1]', null=True, verbose_name='输出示例 (JSON)'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='param_names',
            field=models.CharField(blank=True, help_text='例如: nums,target 或 a,b', max_length=200, verbose_name='参数名 (逗号分隔)'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='input_format',
            field=models.TextField(blank=True, help_text='例如：第一行包含两个整数 A 和 B。', null=True, verbose_name='输入格式说明'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='output_format',
            field=models.TextField(blank=True, help_text='例如：输出一个整数，表示 A+B 的结果。', null=True, verbose_name='输出格式说明'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='sample_input',
            field=models.TextField(blank=True, null=True, verbose_name='样例输入 (文本)'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='sample_output',
            field=models.TextField(blank=True, null=True, verbose_name='样例输出 (文本)'),
        ),
    ]
