# Generated by Django 6.0.3 on 2026-03-11 13:55

import django.db.models.deletion
import programming.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0011_codeproblem_function_name_codeproblem_input_example_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codesubmission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='problemdiscussion',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='codesubmission',
            name='programming_status_838949_idx',
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='data_range',
            field=models.TextField(blank=True, null=True, verbose_name='数据范围'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='function_name',
            field=models.CharField(blank=True, default='', help_text='用户需要实现的函数名，例如: twoSum, add', max_length=100, verbose_name='函数名'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='input_example',
            field=models.JSONField(blank=True, null=True, verbose_name='输入示例'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='input_format',
            field=models.TextField(blank=True, null=True, verbose_name='输入格式'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='output_example',
            field=models.JSONField(blank=True, null=True, verbose_name='输出示例'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='output_format',
            field=models.TextField(blank=True, null=True, verbose_name='输出格式'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='sample_input',
            field=models.TextField(blank=True, null=True, verbose_name='样例输入'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='sample_output',
            field=models.TextField(blank=True, null=True, verbose_name='样例输出'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='solution_text',
            field=models.TextField(blank=True, null=True, verbose_name='官方题解'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='题目来源'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='算法标签'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='test_cases',
            field=models.JSONField(blank=True, default=list, validators=[programming.models.validate_test_cases_json], verbose_name='测试用例集 (JSON)'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='video_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='视频链接'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='execution_memory',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='execution_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='判题反馈'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('python', 'Python 3'), ('c', 'C (GCC)'), ('cpp', 'C++ (G++)'), ('java', 'Java')], default='python', max_length=20),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='programming.codeproblem'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error')], default='PD', max_length=10),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problemdiscussion',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problemdiscussion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='problemdiscussion',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='programming.codeproblem'),
        ),
        migrations.AlterField(
            model_name='problemdiscussion',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='problemdiscussion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='problemdiscussion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
