# Generated by Django 6.0.3 on 2026-03-13 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0012_alter_codesubmission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
            ],
            options={
                'verbose_name': '题目收藏',
                'verbose_name_plural': '题目收藏',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='codesubmission',
            options={'ordering': ['-submitted_at'], 'verbose_name': '代码提交记录', 'verbose_name_plural': '代码提交记录'},
        ),
        migrations.AlterModelOptions(
            name='problemdiscussion',
            options={'ordering': ['-created_at'], 'verbose_name': '题目讨论', 'verbose_name_plural': '题目讨论'},
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='mode',
            field=models.CharField(choices=[('practice', '练习模式'), ('exam', '考试模式')], default='practice', max_length=20, verbose_name='作答模式'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='execution_memory',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='运行内存(KB)'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='execution_time',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='运行时间(ms)'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('python', 'Python 3'), ('c', 'C (GCC)'), ('cpp', 'C++ (G++)'), ('java', 'Java')], default='python', max_length=20, verbose_name='编程语言'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='programming.codeproblem', verbose_name='所属题目'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error')], default='PD', max_length=10, verbose_name='判题状态'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='提交用户'),
        ),
        migrations.AlterField(
            model_name='problemdiscussion',
            name='content',
            field=models.TextField(verbose_name='讨论内容'),
        ),
        migrations.AlterField(
            model_name='problemdiscussion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='problemdiscussion',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='programming.codeproblem', verbose_name='所属题目'),
        ),
        migrations.AlterField(
            model_name='problemdiscussion',
            name='title',
            field=models.CharField(max_length=200, verbose_name='讨论标题'),
        ),
        migrations.AlterField(
            model_name='problemdiscussion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='problemdiscussion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发布用户'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['user', 'problem', 'mode'], name='programming_user_id_41c778_idx'),
        ),
        migrations.AddField(
            model_name='problemfavorite',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_users', to='programming.codeproblem', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='problemfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_problems', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='problemfavorite',
            index=models.Index(fields=['user', 'problem'], name='programming_user_id_d3eaca_idx'),
        ),
        migrations.AddConstraint(
            model_name='problemfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'problem'), name='unique_user_problem_favorite'),
        ),
    ]
