# Generated by Django 6.0.3 on 2026-03-26 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0013_problemfavorite_alter_codesubmission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codeproblem',
            name='category',
            field=models.CharField(choices=[('基础', '基础'), ('数组', '数组'), ('字符串', '字符串'), ('哈希', '哈希'), ('双指针', '双指针'), ('栈', '栈 / 队列'), ('链表', '链表'), ('二分', '二分查找'), ('贪心', '贪心'), ('动态规划', '动态规划'), ('树', '树'), ('图', '图'), ('回溯', '回溯'), ('数学', '数学')], default='基础', help_text='例如：数组、动态规划、树、图等', max_length=50, verbose_name='主分类'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=15, verbose_name='预估完成时长（分钟）'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='knowledge_points',
            field=models.CharField(blank=True, default='', help_text='多个知识点使用英文逗号分隔，例如：前缀和,枚举,边界处理', max_length=255, verbose_name='知识点'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='question_type',
            field=models.CharField(choices=[('function', '函数补全'), ('acm', '标准输入输出')], default='function', max_length=20, verbose_name='题目形式'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='recommend_stage',
            field=models.CharField(choices=[('入门', '入门'), ('提升', '提升'), ('进阶', '进阶'), ('冲刺', '冲刺')], default='入门', max_length=20, verbose_name='推荐阶段'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='supported_languages',
            field=models.CharField(blank=True, default='python,c,cpp,java', help_text='多个语言使用英文逗号分隔，例如：python,cpp,java', max_length=255, verbose_name='支持语言'),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='算法标签'),
        ),
        migrations.AddIndex(
            model_name='codeproblem',
            index=models.Index(fields=['difficulty'], name='programming_difficu_afb870_idx'),
        ),
        migrations.AddIndex(
            model_name='codeproblem',
            index=models.Index(fields=['category'], name='programming_categor_85620b_idx'),
        ),
        migrations.AddIndex(
            model_name='codeproblem',
            index=models.Index(fields=['recommend_stage'], name='programming_recomme_9b1340_idx'),
        ),
        migrations.AddIndex(
            model_name='codeproblem',
            index=models.Index(fields=['source'], name='programming_source_9c87df_idx'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['status'], name='programming_status_838949_idx'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['language'], name='programming_languag_8e0c26_idx'),
        ),
    ]
