# Generated by Django 6.0.3 on 2026-03-26 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0014_codeproblem_category_codeproblem_estimated_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProblemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未做'), ('tried', '已尝试'), ('passed', '已通过'), ('needs_work', '待攻克')], default='not_started', max_length=20, verbose_name='学习状态')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='尝试次数')),
                ('passed_count', models.PositiveIntegerField(default=0, verbose_name='通过次数')),
                ('first_passed_at', models.DateTimeField(blank=True, null=True, verbose_name='首次通过时间')),
                ('last_submit_at', models.DateTimeField(blank=True, null=True, verbose_name='最近提交时间')),
                ('wrong_count', models.PositiveIntegerField(default=0, verbose_name='错误次数')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='programming.codeproblem', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_statuses', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户题目状态',
                'verbose_name_plural': '用户题目状态',
                'indexes': [models.Index(fields=['user', 'status'], name='programming_user_id_0f1ac7_idx'), models.Index(fields=['problem', 'status'], name='programming_problem_ae718b_idx'), models.Index(fields=['user', 'problem'], name='programming_user_id_6a061e_idx')],
                'unique_together': {('user', 'problem')},
            },
        ),
    ]
