# Generated by Django 6.0.3 on 2026-03-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0015_userproblemstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeproblem',
            name='is_for_challenge',
            field=models.BooleanField(default=False, verbose_name='适合挑战拓展'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='is_for_improvement',
            field=models.BooleanField(default=True, verbose_name='适合巩固提升'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='is_for_weakness_fix',
            field=models.BooleanField(default=True, verbose_name='适合补弱'),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='recommendation_weight',
            field=models.PositiveIntegerField(default=1, help_text='数值越高，越容易在推荐列表中靠前显示。', verbose_name='推荐权重'),
        ),
        migrations.AddIndex(
            model_name='codeproblem',
            index=models.Index(fields=['recommendation_weight'], name='programming_recomme_8389eb_idx'),
        ),
    ]
