# Generated by Django 6.0.3 on 2026-03-11 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_post_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(verbose_name='题目描述')),
                ('difficulty', models.CharField(choices=[('简单', '简单'), ('中等', '中等'), ('困难', '困难')], default='简单', max_length=20, verbose_name='难度')),
                ('tags', models.CharField(blank=True, help_text='例如: 数组,二分查找', max_length=300, verbose_name='标签 (逗号分隔)')),
                ('function_name', models.CharField(default='solve', help_text='用户需要实现的函数名', max_length=100, verbose_name='函数名')),
                ('param_names', models.CharField(blank=True, help_text='例如: nums,target', max_length=200, verbose_name='参数名 (逗号分隔)')),
                ('input_example', models.JSONField(blank=True, help_text="JSON 格式，如: {'nums': [1,2], 'target': 3}", null=True, verbose_name='输入示例')),
                ('output_example', models.JSONField(blank=True, help_text='JSON 格式，如: 1', null=True, verbose_name='输出示例')),
                ('test_cases', models.JSONField(default=list, help_text='JSON 列表，每项包含 input 和 expected', verbose_name='测试用例列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '编程题目',
                'verbose_name_plural': '编程题目',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='代码内容')),
                ('language', models.CharField(default='cpp', max_length=50, verbose_name='编程语言')),
                ('status', models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compile Error'), ('PD', 'Pending')], default='PD', max_length=10, verbose_name='状态')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='运行时间 (ms)')),
                ('memory_usage', models.IntegerField(blank=True, null=True, verbose_name='内存消耗 (KB)')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='community.codeproblem', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交用户')),
            ],
            options={
                'verbose_name': '提交记录',
                'verbose_name_plural': '提交记录',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
