# Generated by Django 6.0.3 on 2026-03-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_codeproblem_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
        migrations.DeleteModel(
            name='CodeProblem',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
